import Head from 'next/head'
import CryptoList from '../comp/cryptoList';
import SearchBar from '../comp/SearchBar'
import { useState } from 'react'
import Footer from '../comp/layouts/Footer'
import Navbar from '../comp/layouts/Navbar'

export default function Home({cryptos}) {

  const [search, setSearch] = useState('');

  const cryptoSearched = cryptos.filter(crypto =>
    crypto.name.toLowerCase().includes(search.toLowerCase())
  )
  
  const handleChange = e => {
    e.preventDefault();
    setSearch(e.target.value.toLowerCase());
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchBar type='text' placeholder='search' onChange={handleChange}/>
      <CryptoList cryptos={cryptoSearched}/>
    </div>
  )
}


export const getServerSideProps = async () => {
  const res = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=20&page=1&sparkline=false');
  const crypto_data = await res.json();

  return {
      props : { cryptos : crypto_data }
  }
}

